### ISSUE TITLE
Update go-libp2p to 0.18.x

### ISSUE THREAD

**Issue by mudler** [mudler/edgevpn#7]
- [x] libp2p/go-libp2p-quic-transport#260
- [x] New data race after  libp2p/go-libp2p-quic-transport#260 - to debug still https://github.com/mudler/edgevpn/actions/runs/1803572851
- [x] Disable 64bit Darwin builds due to new gosigar dependency
- [x] https://github.com/mudler/edgevpn/pull/10 - due to memleak. still collecting pprofs
- [x] https://github.com/mudler/edgevpn/issues/9 - disable darwin builds
- [x] https://github.com/mudler/edgevpn/issues/11
- [x] https://github.com/libp2p/go-libp2p/releases/tag/v0.18.0-rc5

Branch with reverts: https://github.com/mudler/edgevpn/tree/up/libp2p-0.18
